name: sidewalk_pytorch
channels:
  - pytorch
  - defaults
dependencies:
  - backports=1.0=py27_1
  - backports.functools_lru_cache=1.5=py27_1
  - backports.shutil_get_terminal_size=1.0.0=py27_2
  - backports_abc=0.5=py27h7b3c97b_0
  - blas=1.0=mkl
  - bleach=3.0.2=py27_0
  - ca-certificates=2019.1.23=0
  - certifi=2018.11.29=py27_0
  - cffi=1.11.5=py27he75722e_1
  - configparser=3.5.0=py27_0
  - cycler=0.10.0=py27hc7354d3_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py27_0
  - entrypoints=0.2.3=py27_2
  - enum34=1.1.6=py27_1
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - functools32=3.2.3.2=py27_1
  - futures=3.2.0=py27_0
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.1=144
  - ipaddress=1.0.22=py27_0
  - ipykernel=4.10.0=py27_0
  - ipython=5.8.0=py27_0
  - ipython_genutils=0.2.0=py27_0
  - jinja2=2.10=py27_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py27_0
  - jupyter_client=5.2.4=py27_0
  - jupyter_core=4.4.0=py27_0
  - kiwisolver=1.0.1=py27hf484d3e_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.35=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - markupsafe=1.1.0=py27h7b6447c_0
  - matplotlib=2.2.3=py27hb69df0a_0
  - mistune=0.8.4=py27h7b6447c_0
  - mkl=2019.1=144
  - mkl_fft=1.0.6=py27hd81dba3_0
  - mkl_random=1.0.2=py27hd81dba3_0
  - nb_conda=2.2.1=py27_0
  - nb_conda_kernels=2.2.0=py27_0
  - nbconvert=5.3.1=py27_0
  - nbformat=4.4.0=py27_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.8.2=py27h6bb024c_1
  - notebook=5.7.4=py27_0
  - numpy=1.15.4=py27h7e9f1db_0
  - numpy-base=1.15.4=py27hde5b4d6_0
  - olefile=0.46=py27_0
  - openssl=1.1.1b=h7b6447c_1
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py27_1
  - pathlib2=2.3.3=py27_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py27_0
  - pickleshare=0.7.5=py27_0
  - pillow=5.3.0=py27h34e0f95_0
  - pip=18.1=py27_0
  - prometheus_client=0.5.0=py27_0
  - prompt_toolkit=1.0.15=py27_0
  - ptyprocess=0.6.0=py27_0
  - pycparser=2.19=py27_0
  - pygments=2.3.1=py27_0
  - pyparsing=2.3.0=py27_0
  - pyqt=5.9.2=py27h05f1152_2
  - python=2.7.15=h9bab390_6
  - python-dateutil=2.7.5=py27_0
  - pytorch=1.0.0=py2.7_cuda9.0.176_cudnn7.4.1_1
  - pytz=2018.7=py27_0
  - pyzmq=17.1.2=py27h14c3975_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scandir=1.9.0=py27h14c3975_0
  - send2trash=1.5.0=py27_0
  - setuptools=40.6.3=py27_0
  - simplegeneric=0.8.1=py27_2
  - singledispatch=3.4.0.3=py27h9bcb476_0
  - sip=4.19.8=py27hf484d3e_0
  - six=1.12.0=py27_0
  - sqlite=3.26.0=h7b6447c_0
  - subprocess32=3.5.3=py27h7b6447c_0
  - terminado=0.8.1=py27_1
  - testpath=0.4.2=py27_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.2.1=py_2
  - tornado=5.1.1=py27h7b6447c_0
  - traitlets=4.3.2=py27_0
  - wcwidth=0.1.7=py27h9e3e1ab_0
  - webencodings=0.5.1=py27_1
  - wheel=0.32.3=py27_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.2.5=hf484d3e_1
  - zlib=1.2.11=h7b6447c_3
prefix: /home/gweld/anaconda2/envs/sidewalk_pytorch

